### ISSUE TITLE
Reading checkpoint problem

### ISSUE THREAD

**Issue by Dasona** [amanjhunjhunwala/PSPNet-Tensorflow#2]
I want to training cityscape dataset . 
So I made tfrecord using convert_raw_data.sh.
I tried to training, but I got this error . 

I think this is reading checkpoint file error .
If I want to training different dataset, do I need new checkpoint file different with uploaded checkpoint file in dropbox ? 

Num of classes detected:19
WARNING:tensorflow:From train_semantic_segmentation.py:470 in main.: calling softmax_cross_entropy (from tensorflow.contrib.losses.python.losses.loss_ops) with weight is deprecated and will be removed after 2016-11-25.
Instructions for updating:
`weight` is being deprecated, use `weights`
WARNING:tensorflow:From train_semantic_segmentation.py:543 in main.: merge_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.merge.
Restoring from checkpoint .....
Traceback (most recent call last):
  File "train_semantic_segmentation.py", line 560, in <module>
    tf.app.run()
  File "/home/tf/anaconda2/envs/tensorflow-0.12/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train_semantic_segmentation.py", line 551, in main
    init_fn=_get_init_fn(),
  File "train_semantic_segmentation.py", line 336, in _get_init_fn
    ignore_missing_vars=FLAGS.ignore_missing_vars)
  File "/home/tf/anaconda2/envs/tensorflow-0.12/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 546, in assign_from_checkpoint_fn
    reader = pywrap_tensorflow.NewCheckpointReader(model_path)
  File "/home/tf/anaconda2/envs/tensorflow-0.12/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 110, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/home/tf/anaconda2/envs/tensorflow-0.12/lib/python2.7/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

**Comment by amanjhunjhunwala** [comment]
To train on a new dataset, you need to partially restore the checkpoint such that the final logit layer is not restored. Also the number and mapping of classes would be different and need to be changed accordingly ! 

modify the train_semantic_segmentation.py accordingly !
